name: MorningProof
options:
  bundleIdPrefix: com.rk
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.0.0"
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: "8.0.0"
  SuperwallKit:
    url: https://github.com/superwall/Superwall-iOS
    from: "4.12.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    MARKETING_VERSION: "1.0.4"
    CURRENT_PROJECT_VERSION: "1"

targets:
  MorningProof:
    type: application
    platform: iOS
    sources:
      - path: MorningProof
        excludes:
          - "**/.DS_Store"
      - path: Shared
    dependencies:
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseAnalytics
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: SuperwallKit
        product: SuperwallKit
      # TEMPORARILY DISABLED - Waiting for Family Controls approval
      # - target: MorningProofActivityMonitor
      # - target: MorningProofShieldConfig
      # - target: MorningProofShieldAction
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rk.morningproof
        INFOPLIST_FILE: MorningProof/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: P9ZXADV42A
        CODE_SIGN_STYLE: Automatic
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    entitlements:
      path: MorningProof/Resources/MorningProof.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default
        # TEMPORARILY DISABLED - Waiting for Family Controls approval
        # com.apple.developer.family-controls: true
        com.apple.developer.healthkit: true
        com.apple.security.application-groups:
          - group.com.rk.morningproof
    info:
      path: MorningProof/Resources/Info.plist
      properties:
        CFBundleName: Morning Proof
        CFBundleDisplayName: Morning Proof
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        LSRequiresIPhoneOS: true
        NSSupportsLiveActivities: true
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIRequiresFullScreen: true
        NSCameraUsageDescription: "Morning Proof needs camera access to take photos of your made bed for verification."
        NSPhotoLibraryUsageDescription: "Morning Proof needs photo library access to select bed photos for verification."
        NSHealthShareUsageDescription: "Morning Proof uses your health data to automatically track morning movement and sleep quality."
        NSHealthUpdateUsageDescription: "Morning Proof may save your morning routine data to Health."
        GIDClientID: 591131827329-487r1epolmgvbq8vdf3cje54qlpmi0a3.apps.googleusercontent.com
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - com.googleusercontent.apps.591131827329-487r1epolmgvbq8vdf3cje54qlpmi0a3

  MorningProofTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: MorningProofTests
    dependencies:
      - target: MorningProof

  MorningProofUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: MorningProofUITests
    dependencies:
      - target: MorningProof

  # MARK: - Screen Time Extensions
  # TEMPORARILY DISABLED - Waiting for Family Controls approval
  # Uncomment these targets once all bundle IDs are approved

  # MorningProofActivityMonitor:
  #   type: app-extension
  #   platform: iOS
  #   sources:
  #     - path: DeviceActivityMonitorExtension
  #     - path: Shared
  #   settings:
  #     base:
  #       PRODUCT_BUNDLE_IDENTIFIER: com.rk.morningproof.activitymonitor
  #       DEVELOPMENT_TEAM: P9ZXADV42A
  #       CODE_SIGN_STYLE: Automatic
  #       TARGETED_DEVICE_FAMILY: "1"
  #       SKIP_INSTALL: YES
  #   entitlements:
  #     path: DeviceActivityMonitorExtension/DeviceActivityMonitorExtension.entitlements
  #     properties:
  #       com.apple.developer.family-controls: true
  #       com.apple.security.application-groups:
  #         - group.com.rk.morningproof
  #   info:
  #     path: DeviceActivityMonitorExtension/Info.plist
  #     properties:
  #       CFBundleDisplayName: Morning Proof Activity Monitor
  #       CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
  #       CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  #       CFBundleShortVersionString: $(MARKETING_VERSION)
  #       CFBundlePackageType: XPC!
  #       NSExtension:
  #         NSExtensionPointIdentifier: com.apple.deviceactivity.monitor
  #         NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).DeviceActivityMonitorExtension

  # MorningProofShieldConfig:
  #   type: app-extension
  #   platform: iOS
  #   sources:
  #     - path: ShieldConfigurationExtension
  #     - path: Shared
  #   settings:
  #     base:
  #       PRODUCT_BUNDLE_IDENTIFIER: com.rk.morningproof.shieldconfig
  #       DEVELOPMENT_TEAM: P9ZXADV42A
  #       CODE_SIGN_STYLE: Automatic
  #       TARGETED_DEVICE_FAMILY: "1"
  #       SKIP_INSTALL: YES
  #   entitlements:
  #     path: ShieldConfigurationExtension/ShieldConfigurationExtension.entitlements
  #     properties:
  #       com.apple.developer.family-controls: true
  #       com.apple.security.application-groups:
  #         - group.com.rk.morningproof
  #   info:
  #     path: ShieldConfigurationExtension/Info.plist
  #     properties:
  #       CFBundleDisplayName: Morning Proof Shield Config
  #       CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
  #       CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  #       CFBundleShortVersionString: $(MARKETING_VERSION)
  #       CFBundlePackageType: XPC!
  #       NSExtension:
  #         NSExtensionPointIdentifier: com.apple.shieldconfiguration
  #         NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ShieldConfigurationExtension

  # MorningProofShieldAction:
  #   type: app-extension
  #   platform: iOS
  #   sources:
  #     - path: ShieldActionExtension
  #     - path: Shared
  #   settings:
  #     base:
  #       PRODUCT_BUNDLE_IDENTIFIER: com.rk.morningproof.shieldaction
  #       DEVELOPMENT_TEAM: P9ZXADV42A
  #       CODE_SIGN_STYLE: Automatic
  #       TARGETED_DEVICE_FAMILY: "1"
  #       SKIP_INSTALL: YES
  #   entitlements:
  #     path: ShieldActionExtension/ShieldActionExtension.entitlements
  #     properties:
  #       com.apple.developer.family-controls: true
  #       com.apple.security.application-groups:
  #         - group.com.rk.morningproof
  #   info:
  #     path: ShieldActionExtension/Info.plist
  #     properties:
  #       CFBundleDisplayName: Morning Proof Shield Action
  #       CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
  #       CFBundleVersion: $(CURRENT_PROJECT_VERSION)
  #       CFBundleShortVersionString: $(MARKETING_VERSION)
  #       CFBundlePackageType: XPC!
  #       NSExtension:
  #         NSExtensionPointIdentifier: com.apple.shieldaction
  #         NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ShieldActionExtension

schemes:
  MorningProof:
    build:
      targets:
        MorningProof: all
        MorningProofTests: [test]
        MorningProofUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - MorningProofTests
        - MorningProofUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
